//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace livechart
{
    using System;
    using System.Collections.Generic;
    
    public partial class voicerecord
    {
        public System.DateTime Date { get; set; }
        public Nullable<double> time { get; set; }
        public string username { get; set; }
    }
}
